# The first two are supported funding model platforms and line 6 to 10 are future funding platforms

github: ironclaw-hub
patreon: Ironclaw
//The ones listed below are comming soon. 
predator,inc: Ironclaw.com
Predator.com: This is going to be like discord but a whole lot more fun.
Predator coding platform: This is the coding platform for predator where creators can make anything.
Predadocs: This is the page where all or help documentations are which anyone can look at
Predaslides: This is like powerpoint but has a built in ai(voice or chatbot),graphics,video's,gif's,and so much more.

